repos:
# -   repo: https://github.com/pocc/pre-commit-hooks
#     rev: v1.3.5
#     hooks:
#     -   id: clang-format
#     -   id: clang-tidy
#     -   id: oclint
#     -   id: uncrustify
#     -   id: cppcheck
#     -   id: cpplint
#     -   id: include-what-you-use
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0  # this is optional, use `pre-commit autoupdate` to get the latest rev!
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
