name: Build  

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build
    strategy:
      fail-fast: false
      matrix:
        os: [windows, ubuntu]
        conf: [release, debug]
        arch: [x64]
        exclude:
          - os: ubuntu
            arch: x86
          - os: macos
            arch: x86
    
    runs-on: ${{ matrix.os }}-latest

    steps:
    - uses: actions/checkout@v3
    
    - uses: ashutoshvarma/setup-ninja@master
    - uses: ammaraskar/gcc-problem-matcher@master

    - name: Set preset name
      id: preset
      shell: bash
      run: |
        echo "name=${{ matrix.os }}-${{ matrix.arch }}-${{ matrix.conf }}" | sed s/ubuntu/linux/ >> $GITHUB_OUTPUT

    - name: Set up Windows compiler
      uses: egor-tensin/setup-mingw@v2
      with:
        platform: ${{ matrix.arch }}
    
    - name: Install QT
      if: runner.os == 'windows'
      working-directory: lib/qtbase
      run: |
        configure.bat 
        cmake --build .
        cmake --install .
      shell: pwsh

    - name: Configure CMake
      run: cmake --preset ${{ steps.preset.outputs.name }}

    - name: Build
      run: cmake --build --preset ${{ steps.preset.outputs.name }}

    - name: Test
      run: ctest --timeout 5 --preset ${{ steps.preset.outputs.name }}